- package-lock.json
- package.json
- src/App.js
- src/ComponentSample.js
- src/common.scss
버튼 공통 스타일 작성, 컴포넌트 샘플 페이지 생성 및 작성
> style: create button style, make componentSample.js

- yarn.lock
#10 
스타일 컴포넌트 예제를 쉽게 볼 수 있는 버튼과 예제에 클래스네임 보이게 수정 후 추가
> Add stylesample nav button

- src/Components/Molecules/CarouselCalendar.js
- src/Components/Molecules/style/CarouselCalendar.scss
- src/Reducer/bookingReducer.js
- src/Utils/ultil.js
> feat: complete carousel calendar

- package-lock.json
- src/Components/Pages/MyPage.js
- src/Components/Pages/mypage.scss
- src/Components/Pages/mypageSample.scss
- src/common.scss
마이페이지 레이아웃 작성 및 스타일 작성 (포인트 부분 제외) #18 
common style에 
select css 변경되었습니다.
(.selectWrap 안에서 
select와 .icon.arrowBottom을 함께 사용하는 것으로 변경)
> feat: mypage layout & style

- src/ComponentSample.js
- src/Components/Pages/MyPage.js
- src/Components/Pages/mypage.scss
- src/common.scss
#25 버튼 스타일 리팩토링 및 아이콘 css 위치 이동
> style: button style refactoring

- src/Components/Molecules/BookingMovieList.js
- src/Components/Molecules/Calendar.js
- src/Components/Molecules/CarouselCalendar.js
- src/Components/Molecules/style/BookingMovieList.scss
- src/Components/Molecules/style/Calendar.scss
> feat: Make Movie List Layout

- src/Modules/ModalPortal.js
> feat: Make Modal Portal

- src/Components/Organisms/Main/MainBoxOffice.js
- src/Components/Organisms/NavSample.js
- src/Components/Pages/MovieDetailPage.js
- src/Components/Templates/MovieDetail.js
- src/Router/MainRouter.js
> feat: movieDetailPage init

- src/Components/Molecules/BookingPersonalCounter.js
- src/Components/Molecules/BookingSeatReset.js
- src/Components/Molecules/PopupNotice.js
- src/Components/Organisms/Booking/BookingSelectSeat.js
- src/Components/Organisms/Booking/style/BookingSelectSeat.scss
- src/Reducer/bookingReducer.js
- src/Reducer/index.js
- src/Reducer/modalReducer.js
파일 명 바꾸고 redux 재연결 및 컴포넌트 import 끝났습니다.
selved: #65
> Docs: Changed file name

- src/Components/Molecules/BookingPersonalCounter.js
- src/Components/Molecules/BookingSeatReset.js
- src/Reducer/modalReducer.js
모달 팝업 리듀서 팝업 열기 액션과 팝업 사이즈 지정 액션을 나누었습니다.
solved: #70
> Docs: Modified modal popup reducer

- src/Components/Molecules/BookingMovieList.js
- src/Components/Molecules/BookingTheaterList.js
- src/Components/Molecules/style/BookingMovieList.scss
- src/Components/Molecules/style/BookingTheaterList.scss
- src/Reducer/bookingReducer.js
#54 
빠른예매 페이지에 있는 요소들 전부 상태에 연결 및 그에 필요한 리듀서와 액션 개발
> feat: Make reducer & actions

- src/Components/Atoms/BookingFastTitle.js
- src/Components/Atoms/style/BookingFastTitle.scss
- src/Components/Organisms/Booking/BookingSelectMovie.js
> feat: Make fast booking title

- src/Components/Molecules/BookingInfo.js
- src/Components/Molecules/BookingPersonalCounter.js
- src/Components/Molecules/BookingSeatReset.js
- src/Components/Molecules/style/BookingSeatList.scss
- src/Reducer/modalReducer.js
- src/Utils/ultil.js
좌석 예매 정보 컴포넌트 기능까지 구현 완료했습니다.
solved: #27
> Feat: Finished BookingSeatInfo component feats

- src/Api/api.js
- src/Components/Molecules/BookingSeatList.js
- src/Components/Organisms/SignUpForm.js
회원가입 페이지
- 입력에 따른 경고 문구 출력
- 회원가입 api 연결
solved: #108
> Feat: Connected API in signup page

- src/Api/api.js
- src/Components/Pages/BookingPage.js
- src/Reducer/userInfoReducer.js
> fix: refresh bug fix

- src/Utils/theaterLocation.js
> fix: fix gps error

- src/Components/Organisms/LoginForm.js
- src/Reducer/userInfoReducer.js
- src/Utils/ultil.js
쿠키에 id 저장하게 고침, 로그인 에러 메세지 보내는 것을 미들웨어에서 처리하게 고침
> fix: fix cookie bug & some reducer

- src/Api/api.js
- src/Components/Molecules/BookingInfo.js
- src/Components/Molecules/BookingMovieList.js
- src/Reducer/bookingReducer.js
> fix & refactor: refactoring states refactor, fix no reservation info bug fix

- src/Components/Molecules/BookingInfo.js
- src/Reducer/bookingReducer.js
예약 생성 api를 redux thunk로 제작
solved: #178
> Docs: Rebuild reducer Making Reservation api

- src/Api/api.js
- src/Components/Molecules/BookingInfo.js
- src/Components/Molecules/BookingSeatList.js
- src/Components/Organisms/Booking/BookingSelectSeat.js
- src/Components/Organisms/SignUpForm.js
- src/Reducer/bookingReducer.js
- src/Reducer/bookingSeatReducer.js
- src/Reducer/index.js
- 좌석 holding 로직 추가
- booking reducer 에 priceList 추가 및 컴포넌트에 연결
solved: #176, #177
> Feat: Made feat Holding Seat and Added and Connected priceList state

- src/Api/api.js
- src/Reducer/userInfoReducer.js
> fix: fix mypage detail api

- src/Components/Molecules/ChartBookingRating.js
- src/Components/Molecules/RaderChartKeyPoint.js
- src/Components/Organisms/MainHeader.js
- src/Components/Organisms/MovieDetail/MovieInforWrap.js
- src/Reducer/movieReducer.js
> fix: logout event

- src/Api/api.js
> fix: fix api

- src/Api/api.js
- src/Components/Molecules/RaderChartKeyPoint.js
- src/Components/Organisms/Main/MainBoxOffice.js
- src/Components/Organisms/MovieDetail/MovieDetailWrap.js
- src/Components/Organisms/MovieDetail/MovieInforWrap.js
- src/Reducer/movieReducer.js
상세페이지 관람평,
영화페이지 이슈 해결(컴퍼넌트 초기화안되는부분)
> fix: movie page error

- src/Api/api.js
- src/Components/Organisms/NavSample.js
- src/Reducer/userInfoReducer.js
> fix: members api address

- src/Components/Molecules/BookingPersonalCounter.js
- src/Components/Molecules/BookingSeatReset.js
더블 팝업 뜨는 것 수정
예약 생성 시 로그인 상태 확인해서 처리하는 기능 추가
solved: #205 , #204
> Fix: Modified double Popup and Feat: Added check Login feature when send reservation

- src/Components/Atoms/style/Loading.scss
- src/Components/Organisms/Booking/BookingSelectSeat.js
- src/Reducer/bookingSeatReducer.js
좌석 초기화 및 선택시 api 요청 중에 로딩 출력
solved: #215
> Feat: Made loading when select Seat and reset seat

- src/Api/api.js
- src/Components/Atoms/SkeletonMainMovies.js
- src/Components/Organisms/Booking/BookingSelectSeat.js
- src/Components/Organisms/Main/MainBoxOffice.js
- src/Components/Organisms/Main/style/MainBoxOffice.scss
- src/Components/Organisms/SignUpForm.js
- src/Reducer/bookingSeatReducer.js
- 구글 회원가입 구현
- 메인페이지에 영화 리스트 애니메이션 구현
- 메인페이지 로딩을 위한 스켈레톤 컴포넌트 보이도록 구현.
solved: #220, #221, #223
> Feat: Made skeleton for loading MainMovies, Make Google sign-up and Style: Made animation in main Movie list

- src/Components/Atoms/SkeletonDetailPage.js
- src/Components/Organisms/MainHeader.js
- src/Components/Organisms/MovieDetail/MovieDetailWrap.js
- src/Components/Organisms/MovieDetail/MovieInforWrap.js
- src/Components/Organisms/style/MainHeader.scss
- src/Reducer/movieReducer.js
> feat: make skeleton in detail page   and  error in header

- src/Api/api.js
- src/Components/Organisms/SignUpForm.js
- src/Components/Organisms/style/SignUpForm.scss
> Feat: Connected Google signup Api

- src/Components/Pages/MyPage.js
- src/Reducer/userInfoReducer.js
> fix: fix mypage reloading bug

- src/Api/api.js
- src/Components/Molecules/BookingTheaterList.js
- src/Components/Organisms/LoginForm.js
- src/Reducer/userInfoReducer.js
> fix:  socialLogin api address

- src/Api/api.js
- src/Components/Molecules/BookingCancel.js
- src/Components/Organisms/LoginForm.js
- src/Components/Organisms/MainHeader.js
- src/Components/Organisms/MyPage/BookingHistoryWrap.js
- src/Components/Organisms/MyPage/MypageDashBoard.js
- src/Reducer/userInfoReducer.js
> feat: Make cancel payment func

- src/Components/Molecules/MovieDetailComment.js
- src/Components/Organisms/Main/MainNotice.js
- src/Components/Organisms/MovieDetail/MovieInforWrap.js
> fix : css code

- README.md
README.md 문서 내용 삽입
- 프로젝트 명
- 사용 기술
- 시작 방법
- 팀원
- 개발 동기
- 메인 기능
solved: #268
> Docs: Added content README.md

- public/index.html
- public/manifest.json
모바일 링크 용 이미지 및 설명 편집
solved: #272
> Docs: Edit description and icons

- src/App.js
- src/Components/Organisms/Footer.js
- src/Components/Organisms/Main/MainBoxOffice.js
- src/Components/Organisms/Main/MainCuration.js
- src/Components/Organisms/Main/MainLink.js
- src/Components/Organisms/Main/style/MainCuration.scss
- src/Components/Organisms/Main/style/MainLink.scss
- src/Components/Organisms/MainHeader.js
- src/Components/Organisms/MovieDetail/MovieDetailWrap.js
- src/Components/Organisms/style/MainHeader.scss
- src/Reducer/movieReducer.js
- src/app.scss
Reverts OmegaBox/React_Frontend#276
> Revert "fix: main page scss code"

- src/Components/Molecules/BookingTheaterList.js
- src/Utils/theaterLocation.js
> fix: fix infinity gps request

- public/index.html
- src/Components/Organisms/Footer.js
- src/Components/Organisms/Header.js
- src/Components/Organisms/Main/MainBoxOffice.js
- src/Components/Organisms/Main/MainCuration.js
- src/Components/Organisms/Main/MainTheater.js
- src/Components/Organisms/Main/style/MainBoxOffice.scss
- src/Components/Organisms/MainHeader.js
- src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
- src/Components/Pages/BookingPage.js
- src/Components/Pages/EventPage.js
- src/Components/Pages/MyPage.js
- src/Components/Pages/style/mypage.scss
- src/Components/Templates/Main.js
- src/Reducer/movieReducer.js
> fix: fix styles
